version: '3.5'
services: 
  rediscache:
    image: redis 
    ports: 
      - 6379 
  backend:
    image: 2_10_backend
    environment: 
      - REDIS=rediscache
      - DB_NAME=backenddb
      - DB_USERNAME=backenduser
      - DB_PASSWORD=backend123
      - DB_HOST=db
    ports: 
      - 8000:8000  
  frontend:
    image: 2_10_frontend
    ports: 
      - 5000:5000
  nginx:
    image: nginx
    environment: 
      - NGINX_PORT=80
    ports: 
      - 80:80
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf 
  db:
    image: postgres 
    restart: unless-stopped   
    environment: 
      - POSTGRES_USER=backenduser
      - POSTGRES_PASSWORD=backend123
      - POSTGRES_DB=backenddb