version: '3.5'
services: 
  rediscache:
    image: redis 
    ports: 
      - 6379 
  backend:
    image: 1_12_backend
    environment: 
      - REDIS=rediscache
    ports: 
      - 8000:8000  
  frontend:
    image: 1_12_front
    ports: 
      - 5000:5000