version: '3.5'
services: 
  rediscache:
    image: redis 
    ports: 
      - 6379 
  backend:
    image: 1_12_backend
    environment: 
      - REDIS=rediscache
      - DB_NAME=backenddb
      - DB_USERNAME=backenduser
      - DB_PASSWORD=backend123
      - DB_HOST=db
    ports: 
      - 8000:8000  
  frontend:
    image: 1_12_front
    ports: 
      - 5000:5000
  db:
    image: postgres 
    restart: unless-stopped   
    environment: 
      - POSTGRES_USER=backenduser
      - POSTGRES_PASSWORD=backend123
      - POSTGRES_DB=backenddb